default:
    path: /
    defaults:
        _controller: StmolHuddleBundle:Default:index

new_meeting:
    path: /new
    defaults:
        _controller: StmolHuddleBundle:Meeting:new

show_meeting:
    path: /m/{url}
    defaults:
        _controller: StmolHuddleBundle:Meeting:show

edit_meeting:
    path: /m/{url}/edit
    defaults:
        _controller: StmolHuddleBundle:Meeting:edit

change_state_at_meeting:
    path: /m/{url}/member/{action}
    defaults:
        _controller: StmolHuddleBundle:Member:changeState
    requirements:
        action: go|deny

manage_member:
    path: /m/{url}/member/{id}/{action}
    defaults:
        _controller: StmolHuddleBundle:Member:manage
    requirements:
        id: \d+
        action: remove|restore