default:
    path: /
    defaults:
        _controller: StmolHuddleBundle:Default:index

new_meeting:
    path: /new
    defaults:
        _controller: StmolHuddleBundle:Meeting:new

show_meeting:
    path: /m/{url}
    defaults:
        _controller: StmolHuddleBundle:Meeting:show

edit_meeting:
    path: /m/{url}/edit
    defaults:
        _controller: StmolHuddleBundle:Meeting:edit
