parameters:
    stmol_huddle.cookie.user_secret: "user"
#    stmol_huddle.example.class: Stmol\HuddleBundle\Example

services:
    # Service: MeetingManager
    stmol_huddle.meeting_manager:
        class: Stmol\HuddleBundle\Services\MeetingManager
        arguments: ["@doctrine.orm.entity_manager"]
    # Service: MemberManager
    stmol_huddle.member_manager:
        class: Stmol\HuddleBundle\Services\MemberManager
        arguments: ["@doctrine.orm.entity_manager"]
    # Form: Meeting
    stmol_huddle.form.type.meeting:
        class: Stmol\HuddleBundle\Form\MeetingType
        tags:
            - { name: form.type, alias: meeting }
    # Form: Member
    stmol_huddle.form.type.member:
        class: Stmol\HuddleBundle\Form\MemberType
        tags:
            - { name: form.type, alias: member }
    # Form: NewMeeting
    stmol_huddle.form.type.new_meeting:
        class: Stmol\HuddleBundle\Form\NewMeetingType
        tags:
            - { name: form.type, alias: new_meeting }
    # Custom user provider
    #stmol_huddle.user_provider:
    #    class: Stmol\HuddleBundle\Security\User\UserProvider
    #    arguments: ["@doctrine.orm.entity_manager"]
    # Authentication provider by cookie
    by_cookie.security.authentication.provider:
        class:  Stmol\HuddleBundle\Security\Authentication\Provider\CookieAuthenticationProvider
        arguments: [""]
    # Authentication listener by cookie
    by_cookie.security.authentication.listener:
        class:  Stmol\HuddleBundle\Security\Firewall\CookieAuthenticationListener
        arguments: ["@security.context", "@security.authentication.manager", %stmol_huddle.cookie.user_secret%]
#    stmol_huddle.example:
#        class: %stmol_huddle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
